// Package markdown renders a Wails API schema as linked Markdown files.
package markdown

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/AmadoMuerte/wailsdoc/schema"
)

const warning = "<!-- Generated by wailsdoc. Do not edit manually. -->\n\n"

type Coverage struct {
	Controllers           int
	DocumentedControllers int
	Methods               int
	DocumentedMethods     int
	Types                 int
	DocumentedTypes       int
	Warnings              []string
}

type usage struct {
	Controller string
	Method     string
	Kind       string
	Name       string
	Type       string
}

func Render(api schema.API, outputDir string) (Coverage, error) {
	return RenderTitle(api, outputDir, "Wails API")
}

func RenderTitle(api schema.API, outputDir, title string) (Coverage, error) {
	controllers := append([]schema.Controller(nil), api.Controllers...)
	types := append([]schema.Type(nil), api.Types...)
	sort.Slice(controllers, func(i, j int) bool { return controllers[i].Name < controllers[j].Name })
	sort.Slice(types, func(i, j int) bool { return types[i].QualifiedName < types[j].QualifiedName })
	for index := range controllers {
		sort.Slice(controllers[index].Methods, func(i, j int) bool { return controllers[index].Methods[i].Name < controllers[index].Methods[j].Name })
	}

	typeFiles := allocateTypeFiles(types)
	localPackages := map[string]bool{}
	for _, typ := range types {
		localPackages[packageName(typ.QualifiedName)] = true
	}
	for _, controller := range controllers {
		localPackages[packageName(controller.QualifiedName)] = true
	}
	usages := usagesOf(controllers, types, typeFiles)
	typeIndex := make(map[string]schema.Type, len(types))
	for _, typ := range types {
		typeIndex[typ.QualifiedName] = typ
	}
	coverage := coverageOf(controllers, types)
	coverage.Warnings = unresolvedWarnings(controllers, types, typeFiles, localPackages)

	temporary := outputDir + ".tmp"
	if err := os.RemoveAll(temporary); err != nil {
		return Coverage{}, fmt.Errorf("remove temporary output: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(temporary, "controllers"), 0o755); err != nil {
		return Coverage{}, fmt.Errorf("create controller output: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(temporary, "types"), 0o755); err != nil {
		return Coverage{}, fmt.Errorf("create type output: %w", err)
	}
	if err := write(filepath.Join(temporary, "README.md"), renderIndex(title, controllers, types, typeFiles)); err != nil {
		return Coverage{}, err
	}
	if err := write(filepath.Join(temporary, "METHODS.md"), renderMethodIndex(controllers)); err != nil {
		return Coverage{}, err
	}
	for _, controller := range controllers {
		if err := write(filepath.Join(temporary, "controllers", controller.Name+".md"), renderController(controller, typeFiles, typeIndex)); err != nil {
			return Coverage{}, err
		}
	}
	for _, typ := range types {
		if err := write(filepath.Join(temporary, "types", typeFiles[typ.QualifiedName]), renderType(typ, typeFiles, typeIndex, usages[typ.QualifiedName])); err != nil {
			return Coverage{}, err
		}
	}
	if err := os.RemoveAll(outputDir); err != nil {
		return Coverage{}, fmt.Errorf("replace output: %w", err)
	}
	if err := os.Rename(temporary, outputDir); err != nil {
		return Coverage{}, fmt.Errorf("replace output: %w", err)
	}
	return coverage, nil
}

func coverageOf(controllers []schema.Controller, types []schema.Type) Coverage {
	result := Coverage{Controllers: len(controllers), Types: len(types)}
	for _, controller := range controllers {
		if controller.Description != "" {
			result.DocumentedControllers++
		}
		result.Methods += len(controller.Methods)
		for _, method := range controller.Methods {
			if method.Description != "" {
				result.DocumentedMethods++
			}
		}
	}
	for _, typ := range types {
		if typ.Description != "" {
			result.DocumentedTypes++
		}
	}
	return result
}

func renderIndex(title string, controllers []schema.Controller, types []schema.Type, typeFiles map[string]string) string {
	var output strings.Builder
	fmt.Fprintf(&output, "# %s\n\n", title)
	output.WriteString(warning)
	output.WriteString("Generated automatically from the public Wails backend API.\n\n")
	methodCount := 0
	for _, controller := range controllers {
		methodCount += len(controller.Methods)
	}
	fmt.Fprintf(&output, "- Controllers: %d\n- Methods: %d\n- Types: %d\n\n", len(controllers), methodCount, len(types))
	output.WriteString("## Controllers\n\n| Controller | Methods | Description |\n| --- | ---: | --- |\n")
	for _, controller := range controllers {
		fmt.Fprintf(&output, "| [%s](controllers/%s.md) | %d | %s |\n", controller.Name, controller.Name, len(controller.Methods), tableText(controller.Description))
	}
	output.WriteString("\n## Methods\n\nSee the [global method index](METHODS.md).\n\n## Types\n\n")
	for _, typ := range types {
		fmt.Fprintf(&output, "- [%s](types/%s)\n", typeLabel(typ, types), typeFiles[typ.QualifiedName])
	}
	return output.String()
}

func renderMethodIndex(controllers []schema.Controller) string {
	var output strings.Builder
	output.WriteString("# Wails API Methods\n\n")
	output.WriteString(warning)
	output.WriteString("| Method | Controller | Returns | Description |\n| --- | --- | --- | --- |\n")
	for _, controller := range controllers {
		for _, method := range controller.Methods {
			fmt.Fprintf(&output, "| [%s](controllers/%s.md#%s) | [%s](controllers/%s.md) | %s | %s |\n", method.Name, controller.Name, anchor(method.Name), controller.Name, controller.Name, tableCode(tsReturnType(method)), tableText(method.Description))
		}
	}
	return output.String()
}

func renderController(controller schema.Controller, typeFiles map[string]string, types map[string]schema.Type) string {
	var output strings.Builder
	fmt.Fprintf(&output, "# %s\n\n", controller.Name)
	output.WriteString(warning)
	if controller.Description != "" {
		output.WriteString(controller.Description + "\n\n")
	}
	referenced := map[string]bool{}
	for _, method := range controller.Methods {
		for _, parameter := range method.Parameters {
			for _, reference := range refs(parameter.TypeRef, parameter.TypeRefs) {
				if _, ok := typeFiles[reference]; ok {
					referenced[reference] = true
				}
			}
		}
		for _, result := range method.Returns {
			for _, reference := range refs(result.TypeRef, result.TypeRefs) {
				if _, ok := typeFiles[reference]; ok {
					referenced[reference] = true
				}
			}
		}
	}
	fmt.Fprintf(&output, "- Methods: %d\n- Referenced types: %d\n\n", len(controller.Methods), len(referenced))
	output.WriteString("## Methods\n\n")
	for _, method := range controller.Methods {
		fmt.Fprintf(&output, "- [%s](#%s)\n", method.Name, anchor(method.Name))
	}
	for _, method := range controller.Methods {
		fmt.Fprintf(&output, "\n## %s\n", method.Name)
		if method.Description != "" {
			output.WriteString("\n" + method.Description + "\n")
		}
		fmt.Fprintf(&output, "\n### Go\n\n```go\n%s\n```\n\n### TypeScript\n\n```ts\n%s\n```\n", signature(method), tsSignature(method))
		if len(method.Parameters) > 0 {
			output.WriteString("\n### Parameters\n\n| Name | Type |\n| --- | --- |\n")
			for _, parameter := range method.Parameters {
				fmt.Fprintf(&output, "| `%s` | %s |\n", parameter.Name, renderGoType(parameter.GoType, parameter.TypeRef, typeFiles, "../types/"))
			}
		}
		if hasValueReturn(method) {
			output.WriteString("\n### Returns\n\n| Go type | TypeScript type |\n| --- | --- |\n")
			for _, result := range method.Returns {
				if result.GoType == "error" {
					continue
				}
				fmt.Fprintf(&output, "| %s | %s |\n", renderGoType(result.GoType, result.TypeRef, typeFiles, "../types/"), tableCode(valueTSType(result.TSType, result.GoType)))
			}
		}
		if len(method.Errors) > 0 {
			output.WriteString("\n### Errors\n\n")
			for _, documentedError := range method.Errors {
				fmt.Fprintf(&output, "- `%s`", documentedError.Code)
				if documentedError.Description != "" {
					fmt.Fprintf(&output, ": %s", documentedError.Description)
				}
				output.WriteString("\n")
			}
		}
		output.WriteString("\n### Example\n\n```ts\n" + tsExample(method, types) + "\n```\n")
		if method.Source.File != "" {
			output.WriteString("\n### Source\n\n`")
			output.WriteString(method.Source.File)
			if method.Source.Line > 0 {
				fmt.Fprintf(&output, ":%d", method.Source.Line)
			}
			output.WriteString("`\n")
		}
	}
	return output.String()
}

func renderType(typ schema.Type, typeFiles map[string]string, types map[string]schema.Type, usages []usage) string {
	var output strings.Builder
	fmt.Fprintf(&output, "# %s\n\n", typ.Name)
	output.WriteString(warning)
	if typ.Description != "" {
		output.WriteString(typ.Description + "\n")
	}
	if typ.Kind == "struct" {
		output.WriteString("\n## Kind\n\n`struct`\n")
	} else if typ.GoType != "" {
		output.WriteString("\n## Type\n\n```go\n" + typ.GoType + "\n```\n")
	} else {
		output.WriteString("\n## Kind\n\n`" + typ.Kind + "`\n")
	}
	if len(typ.Fields) > 0 {
		hasDescriptions := false
		for _, field := range typ.Fields {
			hasDescriptions = hasDescriptions || field.Description != ""
		}
		output.WriteString("\n## Fields\n\n| Go field | JSON field | Go type | TypeScript type | Optional | Nullable |")
		if hasDescriptions {
			output.WriteString(" Description |")
		}
		output.WriteString("\n| --- | --- | --- | --- | --- | --- |")
		if hasDescriptions {
			output.WriteString(" --- |")
		}
		output.WriteString("\n")
		for _, field := range typ.Fields {
			optional := "No"
			if field.OmitEmpty {
				optional = "Yes"
			}
			nullable := "No"
			if field.Nullable || strings.HasPrefix(field.GoType, "*") {
				nullable = "Yes"
			}
			fmt.Fprintf(&output, "| `%s` | `%s` | %s | %s | %s | %s |", field.Name, field.JSONName, renderGoType(field.GoType, field.TypeRef, typeFiles, ""), tableCode(valueTSType(field.TSType, field.GoType)), optional, nullable)
			if hasDescriptions {
				fmt.Fprintf(&output, " %s |", tableText(field.Description))
			}
			output.WriteString("\n")
		}
	}
	if len(usages) > 0 {
		output.WriteString("\n## Used by\n\n")
		for _, use := range usages {
			if use.Controller != "" {
				fmt.Fprintf(&output, "- [%s.%s](../controllers/%s.md#%s) — %s", use.Controller, use.Method, use.Controller, anchor(use.Method), use.Kind)
			} else {
				fmt.Fprintf(&output, "- [%s](%s) — field", typeLabel(types[use.Type], mapValues(types)), typeFiles[use.Type])
			}
			if use.Name != "" {
				fmt.Fprintf(&output, " `%s`", use.Name)
			}
			output.WriteString("\n")
		}
	}
	related := relatedTypes(typ, typeFiles)
	if len(related) > 0 {
		output.WriteString("\n## Related types\n\n")
		for _, reference := range related {
			fmt.Fprintf(&output, "- [%s](%s)\n", typeLabel(types[reference], mapValues(types)), typeFiles[reference])
		}
	}
	if typ.Source.File != "" {
		output.WriteString("\n## Source\n\n`")
		output.WriteString(typ.Source.File)
		if typ.Source.Line > 0 {
			fmt.Fprintf(&output, ":%d", typ.Source.Line)
		}
		output.WriteString("`\n")
	}
	return output.String()
}

func usagesOf(controllers []schema.Controller, types []schema.Type, typeFiles map[string]string) map[string][]usage {
	result := map[string][]usage{}
	for _, controller := range controllers {
		for _, method := range controller.Methods {
			for _, parameter := range method.Parameters {
				for _, reference := range refs(parameter.TypeRef, parameter.TypeRefs) {
					if _, ok := typeFiles[reference]; ok {
						result[reference] = append(result[reference], usage{Controller: controller.Name, Method: method.Name, Kind: "parameter", Name: parameter.Name})
					}
				}
			}
			for _, returned := range method.Returns {
				for _, reference := range refs(returned.TypeRef, returned.TypeRefs) {
					if _, ok := typeFiles[reference]; ok {
						result[reference] = append(result[reference], usage{Controller: controller.Name, Method: method.Name, Kind: "return value"})
					}
				}
			}
		}
	}
	for _, typ := range types {
		for _, field := range typ.Fields {
			for _, reference := range refs(field.TypeRef, field.TypeRefs) {
				if reference != typ.QualifiedName && typeFiles[reference] != "" {
					result[reference] = append(result[reference], usage{Type: typ.QualifiedName, Name: field.JSONName})
				}
			}
		}
	}
	for reference := range result {
		sort.Slice(result[reference], func(i, j int) bool {
			left, right := result[reference][i], result[reference][j]
			return left.Controller+"\x00"+left.Type+"\x00"+left.Method+"\x00"+left.Kind+"\x00"+left.Name < right.Controller+"\x00"+right.Type+"\x00"+right.Method+"\x00"+right.Kind+"\x00"+right.Name
		})
	}
	return result
}

func unresolvedWarnings(controllers []schema.Controller, types []schema.Type, typeFiles map[string]string, localPackages map[string]bool) []string {
	seen := map[string]bool{}
	check := func(reference string) {
		if reference != "" && typeFiles[reference] == "" && localPackages[packageName(reference)] {
			seen[reference] = true
		}
	}
	for _, controller := range controllers {
		for _, method := range controller.Methods {
			for _, parameter := range method.Parameters {
				for _, reference := range refs(parameter.TypeRef, parameter.TypeRefs) {
					check(reference)
				}
			}
			for _, result := range method.Returns {
				for _, reference := range refs(result.TypeRef, result.TypeRefs) {
					check(reference)
				}
			}
		}
	}
	for _, typ := range types {
		for _, reference := range refs(typ.TypeRef, typ.TypeRefs) {
			check(reference)
		}
		for _, field := range typ.Fields {
			for _, reference := range refs(field.TypeRef, field.TypeRefs) {
				check(reference)
			}
		}
	}
	warnings := make([]string, 0, len(seen))
	for reference := range seen {
		warnings = append(warnings, "project-local type is not documented: "+reference)
	}
	sort.Strings(warnings)
	return warnings
}

func hasValueReturn(method schema.Method) bool {
	for _, result := range method.Returns {
		if result.GoType != "error" {
			return true
		}
	}
	return false
}

func tsSignature(method schema.Method) string {
	parameters := make([]string, len(method.Parameters))
	for index, parameter := range method.Parameters {
		parameters[index] = parameter.Name + ": " + valueTSType(parameter.TSType, parameter.GoType)
	}
	return method.Name + "(" + strings.Join(parameters, ", ") + "): Promise<" + tsReturnType(method) + ">"
}

func tsReturnType(method schema.Method) string {
	var returns []string
	for _, result := range method.Returns {
		if result.GoType != "error" {
			returns = append(returns, valueTSType(result.TSType, result.GoType))
		}
	}
	if len(returns) == 0 {
		return "void"
	}
	if len(returns) == 1 {
		return returns[0]
	}
	return "[" + strings.Join(returns, ", ") + "]"
}

func valueTSType(value, goType string) string {
	if value != "" {
		return value
	}
	value = strings.TrimPrefix(goType, "*")
	nullable := value != goType
	switch {
	case strings.HasPrefix(value, "[]"):
		value = valueTSType("", strings.TrimPrefix(value, "[]")) + "[]"
	case strings.HasPrefix(value, "map["):
		if end := strings.Index(value, "]"); end >= 0 {
			value = "Record<" + valueTSType("", value[4:end]) + ", " + valueTSType("", value[end+1:]) + ">"
		}
	case value == "string":
	case value == "bool":
		value = "boolean"
	case value == "error":
		value = "never"
	case strings.Contains(" int int8 int16 int32 int64 uint uint8 uint16 uint32 uint64 uintptr float32 float64 ", " "+value+" "):
		value = "number"
	default:
		value = typeName(value)
	}
	if nullable {
		value += " | null"
	}
	return value
}

func tsExample(method schema.Method, types map[string]schema.Type) string {
	arguments := make([]string, len(method.Parameters))
	for index, parameter := range method.Parameters {
		arguments[index] = tsValue(parameter.Name, parameter.GoType, parameter.TypeRef, types, 0, map[string]bool{})
	}
	name := lowerFirst(method.Name)
	prefix := "await "
	if tsReturnType(method) != "void" {
		prefix = "const " + name + " = await "
	}
	return prefix + method.Name + "(" + strings.Join(arguments, ", ") + ")"
}

func tsValue(name, goType, reference string, types map[string]schema.Type, depth int, seen map[string]bool) string {
	if strings.HasPrefix(goType, "*") {
		return "null"
	}
	if strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "[") {
		return "[]"
	}
	if strings.HasPrefix(goType, "map[") {
		return "{}"
	}
	if typ, ok := types[reference]; ok && typ.Kind == "struct" {
		if depth >= 2 || seen[reference] {
			return "{}"
		}
		seen[reference] = true
		var fields []string
		for _, field := range typ.Fields {
			if field.OmitEmpty {
				continue
			}
			fields = append(fields, field.JSONName+": "+tsValue(field.JSONName, field.GoType, field.TypeRef, types, depth+1, seen))
		}
		delete(seen, reference)
		return "{ " + strings.Join(fields, ", ") + " }"
	}
	switch valueTSType("", goType) {
	case "string":
		return stringPlaceholder(name)
	case "boolean":
		return "false"
	case "number":
		return "0"
	default:
		return "{}"
	}
}

func stringPlaceholder(name string) string {
	value := strings.ToLower(strings.ReplaceAll(name, "_", ""))
	switch {
	case strings.HasSuffix(value, "id"):
		prefix := strings.TrimSuffix(value, "id")
		if prefix == "" {
			return `"id"`
		}
		return `"` + prefix + `-id"`
	case strings.Contains(value, "email"):
		return `"user@example.com"`
	case strings.Contains(value, "url"):
		return `"https://example.com"`
	case strings.Contains(value, "datadirectory") || strings.Contains(value, "datapath"):
		return `"/path/to/data"`
	case strings.Contains(value, "directory"):
		return `"/path/to/directory"`
	case strings.Contains(value, "path"):
		return `"/path/to/file"`
	case value == "name" || strings.HasSuffix(value, "name") || value == "title":
		return `"Example"`
	case strings.Contains(value, "version"):
		return `"1.0.0"`
	default:
		return `""`
	}
}

func allocateTypeFiles(types []schema.Type) map[string]string {
	counts := map[string]int{}
	for _, typ := range types {
		counts[typ.Name]++
	}
	result, used := map[string]string{}, map[string]bool{}
	for _, typ := range types {
		base := typ.Name
		if counts[typ.Name] > 1 && typ.PackageName != "" {
			base = typ.PackageName + "." + typ.Name
		}
		file := base + ".md"
		if used[file] {
			hash := sha256.Sum256([]byte(typ.QualifiedName))
			file = fmt.Sprintf("%s-%x.md", base, hash[:4])
		}
		used[file], result[typ.QualifiedName] = true, file
	}
	return result
}

func typeLabel(typ schema.Type, types []schema.Type) string {
	for _, other := range types {
		if other.QualifiedName != typ.QualifiedName && other.Name == typ.Name {
			if typ.TSName != "" {
				return typ.TSName
			}
			return typ.QualifiedName
		}
	}
	return typ.Name
}

func mapValues(types map[string]schema.Type) []schema.Type {
	result := make([]schema.Type, 0, len(types))
	for _, typ := range types {
		result = append(result, typ)
	}
	return result
}

func relatedTypes(typ schema.Type, typeFiles map[string]string) []string {
	seen := map[string]bool{}
	for _, reference := range refs(typ.TypeRef, typ.TypeRefs) {
		if reference != typ.QualifiedName && typeFiles[reference] != "" {
			seen[reference] = true
		}
	}
	for _, field := range typ.Fields {
		for _, reference := range refs(field.TypeRef, field.TypeRefs) {
			if reference != typ.QualifiedName && typeFiles[reference] != "" {
				seen[reference] = true
			}
		}
	}
	result := make([]string, 0, len(seen))
	for reference := range seen {
		result = append(result, reference)
	}
	sort.Strings(result)
	return result
}

func refs(primary string, all []string) []string {
	if len(all) > 0 {
		return all
	}
	if primary != "" {
		return []string{primary}
	}
	return nil
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	return strings.ToLower(value[:1]) + value[1:]
}

func signature(method schema.Method) string {
	parameters := make([]string, len(method.Parameters))
	for index, parameter := range method.Parameters {
		parameters[index] = parameter.Name + " " + parameter.GoType
	}
	returns := make([]string, len(method.Returns))
	for index, result := range method.Returns {
		returns[index] = result.GoType
		if result.Name != "" {
			returns[index] = result.Name + " " + result.GoType
		}
	}
	result := method.Name + "(" + strings.Join(parameters, ", ") + ")"
	if len(returns) == 1 {
		return result + " " + returns[0]
	}
	if len(returns) > 1 {
		return result + " (" + strings.Join(returns, ", ") + ")"
	}
	return result
}

func renderGoType(goType, typeRef string, typeFiles map[string]string, prefix string) string {
	file, documented := typeFiles[typeRef]
	if !documented {
		return "`" + goType + "`"
	}
	name := typeName(typeRef)
	index := strings.LastIndex(goType, name)
	if index < 0 {
		return fmt.Sprintf("[`%s`](%s%s)", goType, prefix, file)
	}
	before, after := goType[:index], goType[index+len(name):]
	var output strings.Builder
	if before != "" {
		output.WriteString("`" + before + "`")
	}
	fmt.Fprintf(&output, "[`%s`](%s%s)", name, prefix, file)
	if after != "" {
		output.WriteString("`" + after + "`")
	}
	return output.String()
}

func packageName(qualified string) string {
	if index := strings.LastIndex(qualified, "."); index >= 0 {
		return qualified[:index]
	}
	return ""
}

func typeName(qualified string) string {
	if index := strings.LastIndex(qualified, "."); index >= 0 {
		return qualified[index+1:]
	}
	return qualified
}

func anchor(value string) string { return strings.ToLower(value) }

func tableText(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	return strings.ReplaceAll(value, "\n", "<br>")
}

func tableCode(value string) string { return "`" + tableText(value) + "`" }

func write(path, contents string) error {
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
