package markdown

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/AmadoMuerte/wailsdoc/schema"
)

func TestRender(t *testing.T) {
	api := schema.API{
		SchemaVersion: 2,
		Controllers: []schema.Controller{
			{Name: "ZuluController", QualifiedName: "api.ZuluController", Methods: []schema.Method{{Name: "Missing", Parameters: []schema.Parameter{{Name: "value", GoType: "MissingDTO", TypeRef: "api.MissingDTO"}}}}},
			{
				Name: "ExampleController", QualifiedName: "api.ExampleController", Description: "ExampleController runs examples.",
				Methods: []schema.Method{
					{Name: "Undocumented", Parameters: []schema.Parameter{}, Returns: []schema.Return{}, Source: schema.Source{}},
					{
						Name: "Run", Description: "Run processes the request.", Errors: []schema.Error{{Code: "invalid_request", Description: "the request is invalid"}}, Source: schema.Source{File: "api.go", Line: 42},
						Parameters: []schema.Parameter{
							{Name: "request", GoType: "*Request", TSType: "Request | null", TypeRef: "api.Request", TypeRefs: []string{"api.Request"}, Nullable: true},
							{Name: "items", GoType: "[]*Item", TSType: "(Item | null)[]", TypeRef: "api.Item"},
							{Name: "index", GoType: "map[string]Item", TypeRef: "api.Item"},
							{Name: "when", GoType: "time.Time", TypeRef: "time.Time"},
						},
						Returns: []schema.Return{{GoType: "[]Item", TypeRef: "api.Item"}, {GoType: "error"}},
					},
				},
			},
		},
		Types: []schema.Type{
			{Name: "Request", QualifiedName: "api.Request", Kind: "struct", Description: "Request contains input.", Fields: []schema.Field{
				{Name: "Name", JSONName: "name", GoType: "string", Description: "Human-readable name."},
				{Name: "Item", JSONName: "item", GoType: "*Item", TSType: "Item | null", TypeRef: "api.Item", OmitEmpty: true, Nullable: true},
				{Name: "When", JSONName: "when", GoType: "time.Time", TypeRef: "time.Time"},
			}},
			{Name: "Item", QualifiedName: "api.Item", Kind: "struct", Fields: []schema.Field{}},
			{Name: "Mode", QualifiedName: "api.Mode", Kind: "alias", GoType: "string"},
		},
	}

	output := filepath.Join(t.TempDir(), "docs")
	coverage, err := Render(api, output)
	if err != nil {
		t.Fatal(err)
	}
	if coverage.Controllers != 2 || coverage.DocumentedControllers != 1 || coverage.Methods != 3 || coverage.DocumentedMethods != 1 || coverage.Types != 3 || coverage.DocumentedTypes != 1 {
		t.Fatalf("unexpected coverage: %#v", coverage)
	}
	if len(coverage.Warnings) != 1 || !strings.Contains(coverage.Warnings[0], "api.MissingDTO") {
		t.Fatalf("unexpected warnings: %#v", coverage.Warnings)
	}

	index := readFile(t, filepath.Join(output, "README.md"))
	assertOrder(t, index, "ExampleController", "ZuluController")
	assertOrder(t, index, "Item", "Mode")
	assertOrder(t, index, "Mode", "Request")
	if !strings.Contains(index, "- Controllers: 2") || !strings.Contains(index, "- Methods: 3") || !strings.Contains(index, "- Types: 3") || !strings.Contains(index, "| [ExampleController](controllers/ExampleController.md) | 2 | ExampleController runs examples. |") {
		t.Fatalf("index lacks counts:\n%s", index)
	}

	controller := readFile(t, filepath.Join(output, "controllers", "ExampleController.md"))
	for _, expected := range []string{
		"<!-- Generated by wailsdoc. Do not edit manually. -->",
		"[Run](#run)",
		"Run(request *Request, items []*Item, index map[string]Item, when time.Time) ([]Item, error)",
		"Run(request: Request | null, items: (Item | null)[], index: Record<string, Item>, when: Time): Promise<Item[]>",
		"`invalid_request`: the request is invalid",
		"const run = await Run(null, [], {}, {})",
		"`*`[`Request`](../types/Request.md)",
		"`[]*`[`Item`](../types/Item.md)",
		"`map[string]`[`Item`](../types/Item.md)",
		"| `when` | `time.Time` |",
		"Run processes the request.",
		"`api.go:42`",
		"- Methods: 2",
		"- Referenced types: 2",
	} {
		if !strings.Contains(controller, expected) {
			t.Fatalf("controller lacks %q:\n%s", expected, controller)
		}
	}
	if strings.Contains(controller, "No description") {
		t.Fatal("renderer invented a missing description")
	}
	undocumented := controller[strings.Index(controller, "## Undocumented"):]
	if strings.Contains(undocumented, "### Returns") {
		t.Fatalf("only-error method has an empty returns section:\n%s", undocumented)
	}

	request := readFile(t, filepath.Join(output, "types", "Request.md"))
	for _, expected := range []string{
		"Request contains input.",
		"| `Name` | `name` | `string` | `string` | No | No | Human-readable name. |",
		"| `Item` | `item` | `*`[`Item`](Item.md) | `Item \\| null` | Yes | Yes |",
		"| `When` | `when` | `time.Time` | `Time` | No | No |",
		"[ExampleController.Run](../controllers/ExampleController.md#run) — parameter `request`",
	} {
		if !strings.Contains(request, expected) {
			t.Fatalf("type lacks %q:\n%s", expected, request)
		}
	}
	item := readFile(t, filepath.Join(output, "types", "Item.md"))
	if strings.Contains(item, "Description |") || !strings.Contains(item, "— return value") {
		t.Fatalf("compact fields or return usage missing:\n%s", item)
	}
	mode := readFile(t, filepath.Join(output, "types", "Mode.md"))
	if !strings.Contains(mode, "## Type\n\n```go\nstring\n```") {
		t.Fatalf("alias is not rendered as a type:\n%s", mode)
	}
	methods := readFile(t, filepath.Join(output, "METHODS.md"))
	if !strings.Contains(methods, "[Run](controllers/ExampleController.md#run) | [ExampleController]") {
		t.Fatalf("method index lacks direct method link:\n%s", methods)
	}
	if !strings.Contains(methods, "`Item[]`") {
		t.Fatalf("method index lacks escaped TypeScript return type:\n%s", methods)
	}

	validateLinks(t, output)
	before := snapshot(t, output)
	if _, err := Render(api, output); err != nil {
		t.Fatal(err)
	}
	after := snapshot(t, output)
	if before != after {
		t.Fatal("rendering is not deterministic")
	}
}

func TestTypeScriptSignatures(t *testing.T) {
	tests := []struct {
		name   string
		method schema.Method
		want   string
	}{
		{"only error", schema.Method{Name: "Save", Returns: []schema.Return{{GoType: "error"}}}, "Save(): Promise<void>"},
		{"struct and error", schema.Method{Name: "Get", Returns: []schema.Return{{GoType: "Item", TSType: "Item"}, {GoType: "error"}}}, "Get(): Promise<Item>"},
		{"multiple values", schema.Method{Name: "Pair", Returns: []schema.Return{{GoType: "string"}, {GoType: "int"}, {GoType: "error"}}}, "Pair(): Promise<[string, number]>"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if got := tsSignature(test.method); got != test.want {
				t.Fatalf("tsSignature() = %q, want %q", got, test.want)
			}
		})
	}
}

func validateLinks(t *testing.T, root string) {
	t.Helper()
	linkPattern := regexp.MustCompile(`\[[^]]+\]\(([^)]+)\)`)
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil || entry.IsDir() || filepath.Ext(path) != ".md" {
			return err
		}
		contents := readFile(t, path)
		for _, match := range linkPattern.FindAllStringSubmatch(contents, -1) {
			target := match[1]
			fileTarget, fragment, hasFragment := strings.Cut(target, "#")
			if hasFragment {
				targetContents := contents
				if fileTarget != "" {
					targetContents = readFile(t, filepath.Clean(filepath.Join(filepath.Dir(path), fileTarget)))
				}
				resolved := false
				for _, line := range strings.Split(targetContents, "\n") {
					if strings.HasPrefix(line, "## ") && anchor(strings.TrimPrefix(line, "## ")) == fragment {
						resolved = true
						break
					}
				}
				if !resolved {
					t.Errorf("%s contains unresolved anchor %s", path, target)
				}
				continue
			}
			if _, err := os.Stat(filepath.Clean(filepath.Join(filepath.Dir(path), target))); err != nil {
				t.Errorf("%s contains unresolved link %s", path, target)
			}
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
}

func snapshot(t *testing.T, root string) string {
	t.Helper()
	var files []string
	if err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err == nil && !entry.IsDir() {
			files = append(files, path)
		}
		return err
	}); err != nil {
		t.Fatal(err)
	}
	sort.Strings(files)
	var result strings.Builder
	for _, file := range files {
		result.WriteString(strings.TrimPrefix(file, root))
		result.WriteString(readFile(t, file))
	}
	return result.String()
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(contents)
}

func assertOrder(t *testing.T, value, first, second string) {
	t.Helper()
	if strings.Index(value, first) >= strings.Index(value, second) {
		t.Fatalf("%q is not before %q", first, second)
	}
}
