// Package markdown renders a Wails API schema as linked Markdown files.
package markdown

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/AmadoMuerte/wailsdoc/schema"
)

const warning = "<!-- Generated by wailsdoc. Do not edit manually. -->\n\n"

type Coverage struct {
	Controllers           int
	DocumentedControllers int
	Methods               int
	DocumentedMethods     int
	Types                 int
	DocumentedTypes       int
	Warnings              []string
}

type usage struct {
	Controller string
	Method     string
	Kind       string
	Name       string
}

func Render(api schema.API, outputDir string) (Coverage, error) {
	controllers := append([]schema.Controller(nil), api.Controllers...)
	types := append([]schema.Type(nil), api.Types...)
	sort.Slice(controllers, func(i, j int) bool { return controllers[i].Name < controllers[j].Name })
	sort.Slice(types, func(i, j int) bool { return types[i].QualifiedName < types[j].QualifiedName })
	for index := range controllers {
		sort.Slice(controllers[index].Methods, func(i, j int) bool { return controllers[index].Methods[i].Name < controllers[index].Methods[j].Name })
	}

	typeFiles := make(map[string]string, len(types))
	localPackages := map[string]bool{}
	for _, typ := range types {
		typeFiles[typ.QualifiedName] = typ.Name + ".md"
		localPackages[packageName(typ.QualifiedName)] = true
	}
	for _, controller := range controllers {
		localPackages[packageName(controller.QualifiedName)] = true
	}
	usages := usagesOf(controllers, typeFiles)
	coverage := coverageOf(controllers, types)
	coverage.Warnings = unresolvedWarnings(controllers, types, typeFiles, localPackages)

	temporary := outputDir + ".tmp"
	if err := os.RemoveAll(temporary); err != nil {
		return Coverage{}, fmt.Errorf("remove temporary output: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(temporary, "controllers"), 0o755); err != nil {
		return Coverage{}, fmt.Errorf("create controller output: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(temporary, "types"), 0o755); err != nil {
		return Coverage{}, fmt.Errorf("create type output: %w", err)
	}
	if err := write(filepath.Join(temporary, "README.md"), renderIndex(controllers, types)); err != nil {
		return Coverage{}, err
	}
	if err := write(filepath.Join(temporary, "METHODS.md"), renderMethodIndex(controllers)); err != nil {
		return Coverage{}, err
	}
	for _, controller := range controllers {
		if err := write(filepath.Join(temporary, "controllers", controller.Name+".md"), renderController(controller, typeFiles)); err != nil {
			return Coverage{}, err
		}
	}
	for _, typ := range types {
		if err := write(filepath.Join(temporary, "types", typ.Name+".md"), renderType(typ, typeFiles, usages[typ.QualifiedName])); err != nil {
			return Coverage{}, err
		}
	}
	if err := os.RemoveAll(outputDir); err != nil {
		return Coverage{}, fmt.Errorf("replace output: %w", err)
	}
	if err := os.Rename(temporary, outputDir); err != nil {
		return Coverage{}, fmt.Errorf("replace output: %w", err)
	}
	return coverage, nil
}

func coverageOf(controllers []schema.Controller, types []schema.Type) Coverage {
	result := Coverage{Controllers: len(controllers), Types: len(types)}
	for _, controller := range controllers {
		if controller.Description != "" {
			result.DocumentedControllers++
		}
		result.Methods += len(controller.Methods)
		for _, method := range controller.Methods {
			if method.Description != "" {
				result.DocumentedMethods++
			}
		}
	}
	for _, typ := range types {
		if typ.Description != "" {
			result.DocumentedTypes++
		}
	}
	return result
}

func renderIndex(controllers []schema.Controller, types []schema.Type) string {
	var output strings.Builder
	output.WriteString("# Wails API\n\n")
	output.WriteString(warning)
	output.WriteString("Generated automatically from the public Wails backend API.\n\n")
	methodCount := 0
	for _, controller := range controllers {
		methodCount += len(controller.Methods)
	}
	fmt.Fprintf(&output, "Controllers: %d  \nMethods: %d  \nTypes: %d\n\n", len(controllers), methodCount, len(types))
	output.WriteString("## Controllers\n\n| Controller | Methods | Description |\n| --- | ---: | --- |\n")
	for _, controller := range controllers {
		fmt.Fprintf(&output, "| [%s](controllers/%s.md) | %d | %s |\n", controller.Name, controller.Name, len(controller.Methods), tableText(controller.Description))
	}
	output.WriteString("\n## Methods\n\nSee the [global method index](METHODS.md).\n\n## Types\n\n")
	for _, typ := range types {
		fmt.Fprintf(&output, "- [%s](types/%s.md)\n", typ.Name, typ.Name)
	}
	return output.String()
}

func renderMethodIndex(controllers []schema.Controller) string {
	var output strings.Builder
	output.WriteString("# Wails API Methods\n\n")
	output.WriteString(warning)
	output.WriteString("| Method | Description |\n| --- | --- |\n")
	for _, controller := range controllers {
		for _, method := range controller.Methods {
			fmt.Fprintf(&output, "| [%s.%s](controllers/%s.md#%s) | %s |\n", controller.Name, method.Name, controller.Name, anchor(method.Name), tableText(method.Description))
		}
	}
	return output.String()
}

func renderController(controller schema.Controller, typeFiles map[string]string) string {
	var output strings.Builder
	fmt.Fprintf(&output, "# %s\n\n", controller.Name)
	output.WriteString(warning)
	if controller.Description != "" {
		output.WriteString(controller.Description + "\n\n")
	}
	referenced := map[string]bool{}
	for _, method := range controller.Methods {
		for _, parameter := range method.Parameters {
			if _, ok := typeFiles[parameter.TypeRef]; ok {
				referenced[parameter.TypeRef] = true
			}
		}
		for _, result := range method.Returns {
			if _, ok := typeFiles[result.TypeRef]; ok {
				referenced[result.TypeRef] = true
			}
		}
	}
	fmt.Fprintf(&output, "- Methods: %d\n- Referenced types: %d\n\n", len(controller.Methods), len(referenced))
	output.WriteString("## Methods\n\n")
	for _, method := range controller.Methods {
		fmt.Fprintf(&output, "- [%s](#%s)\n", method.Name, anchor(method.Name))
	}
	for _, method := range controller.Methods {
		fmt.Fprintf(&output, "\n## %s\n\n### Signature\n\n```go\n%s\n```\n", method.Name, signature(method))
		if method.Description != "" {
			output.WriteString("\n### Description\n\n" + method.Description + "\n")
		}
		if len(method.Parameters) > 0 {
			output.WriteString("\n### Parameters\n\n| Name | Type |\n| --- | --- |\n")
			for _, parameter := range method.Parameters {
				fmt.Fprintf(&output, "| `%s` | %s |\n", parameter.Name, renderGoType(parameter.GoType, parameter.TypeRef, typeFiles, "../types/"))
			}
		}
		if len(method.Returns) > 0 {
			output.WriteString("\n### Returns\n\n| Type |\n| --- |\n")
			for _, result := range method.Returns {
				fmt.Fprintf(&output, "| %s |\n", renderGoType(result.GoType, result.TypeRef, typeFiles, "../types/"))
			}
		}
		if method.Source.File != "" {
			output.WriteString("\n### Source\n\n`")
			output.WriteString(method.Source.File)
			if method.Source.Line > 0 {
				fmt.Fprintf(&output, ":%d", method.Source.Line)
			}
			output.WriteString("`\n")
		}
	}
	return output.String()
}

func renderType(typ schema.Type, typeFiles map[string]string, usages []usage) string {
	var output strings.Builder
	fmt.Fprintf(&output, "# %s\n\n", typ.Name)
	output.WriteString(warning)
	if typ.Description != "" {
		output.WriteString(typ.Description + "\n")
	}
	if typ.Kind == "struct" {
		output.WriteString("\n## Kind\n\n`struct`\n")
	} else if typ.GoType != "" {
		output.WriteString("\n## Type\n\n```go\n" + typ.GoType + "\n```\n")
	} else {
		output.WriteString("\n## Kind\n\n`" + typ.Kind + "`\n")
	}
	if len(typ.Fields) > 0 {
		hasDescriptions := false
		for _, field := range typ.Fields {
			hasDescriptions = hasDescriptions || field.Description != ""
		}
		output.WriteString("\n## Fields\n\n| Go field | JSON field | Type | Omit empty |")
		if hasDescriptions {
			output.WriteString(" Description |")
		}
		output.WriteString("\n| --- | --- | --- | --- |")
		if hasDescriptions {
			output.WriteString(" --- |")
		}
		output.WriteString("\n")
		for _, field := range typ.Fields {
			omitEmpty := "No"
			if field.OmitEmpty {
				omitEmpty = "Yes"
			}
			fmt.Fprintf(&output, "| `%s` | `%s` | %s | %s |", field.Name, field.JSONName, renderGoType(field.GoType, field.TypeRef, typeFiles, ""), omitEmpty)
			if hasDescriptions {
				fmt.Fprintf(&output, " %s |", tableText(field.Description))
			}
			output.WriteString("\n")
		}
	}
	if len(usages) > 0 {
		output.WriteString("\n## Used by\n\n")
		for _, use := range usages {
			fmt.Fprintf(&output, "- [%s.%s](../controllers/%s.md#%s) — %s", use.Controller, use.Method, use.Controller, anchor(use.Method), use.Kind)
			if use.Name != "" {
				fmt.Fprintf(&output, " `%s`", use.Name)
			}
			output.WriteString("\n")
		}
	}
	if typ.Source.File != "" {
		output.WriteString("\n## Source\n\n`")
		output.WriteString(typ.Source.File)
		if typ.Source.Line > 0 {
			fmt.Fprintf(&output, ":%d", typ.Source.Line)
		}
		output.WriteString("`\n")
	}
	return output.String()
}

func usagesOf(controllers []schema.Controller, typeFiles map[string]string) map[string][]usage {
	result := map[string][]usage{}
	for _, controller := range controllers {
		for _, method := range controller.Methods {
			for _, parameter := range method.Parameters {
				if _, ok := typeFiles[parameter.TypeRef]; ok {
					result[parameter.TypeRef] = append(result[parameter.TypeRef], usage{Controller: controller.Name, Method: method.Name, Kind: "parameter", Name: parameter.Name})
				}
			}
			for _, returned := range method.Returns {
				if _, ok := typeFiles[returned.TypeRef]; ok {
					result[returned.TypeRef] = append(result[returned.TypeRef], usage{Controller: controller.Name, Method: method.Name, Kind: "return value"})
				}
			}
		}
	}
	for reference := range result {
		sort.Slice(result[reference], func(i, j int) bool {
			left, right := result[reference][i], result[reference][j]
			return left.Controller+"\x00"+left.Method+"\x00"+left.Kind+"\x00"+left.Name < right.Controller+"\x00"+right.Method+"\x00"+right.Kind+"\x00"+right.Name
		})
	}
	return result
}

func unresolvedWarnings(controllers []schema.Controller, types []schema.Type, typeFiles map[string]string, localPackages map[string]bool) []string {
	seen := map[string]bool{}
	check := func(reference string) {
		if reference != "" && typeFiles[reference] == "" && localPackages[packageName(reference)] {
			seen[reference] = true
		}
	}
	for _, controller := range controllers {
		for _, method := range controller.Methods {
			for _, parameter := range method.Parameters {
				check(parameter.TypeRef)
			}
			for _, result := range method.Returns {
				check(result.TypeRef)
			}
		}
	}
	for _, typ := range types {
		check(typ.TypeRef)
		for _, field := range typ.Fields {
			check(field.TypeRef)
		}
	}
	warnings := make([]string, 0, len(seen))
	for reference := range seen {
		warnings = append(warnings, "project-local type is not documented: "+reference)
	}
	sort.Strings(warnings)
	return warnings
}

func signature(method schema.Method) string {
	parameters := make([]string, len(method.Parameters))
	for index, parameter := range method.Parameters {
		parameters[index] = parameter.Name + " " + parameter.GoType
	}
	returns := make([]string, len(method.Returns))
	for index, result := range method.Returns {
		returns[index] = result.GoType
		if result.Name != "" {
			returns[index] = result.Name + " " + result.GoType
		}
	}
	result := method.Name + "(" + strings.Join(parameters, ", ") + ")"
	if len(returns) == 1 {
		return result + " " + returns[0]
	}
	if len(returns) > 1 {
		return result + " (" + strings.Join(returns, ", ") + ")"
	}
	return result
}

func renderGoType(goType, typeRef string, typeFiles map[string]string, prefix string) string {
	file, documented := typeFiles[typeRef]
	if !documented {
		return "`" + goType + "`"
	}
	name := typeName(typeRef)
	index := strings.LastIndex(goType, name)
	if index < 0 {
		return fmt.Sprintf("[`%s`](%s%s)", goType, prefix, file)
	}
	before, after := goType[:index], goType[index+len(name):]
	var output strings.Builder
	if before != "" {
		output.WriteString("`" + before + "`")
	}
	fmt.Fprintf(&output, "[`%s`](%s%s)", name, prefix, file)
	if after != "" {
		output.WriteString("`" + after + "`")
	}
	return output.String()
}

func packageName(qualified string) string {
	if index := strings.LastIndex(qualified, "."); index >= 0 {
		return qualified[:index]
	}
	return ""
}

func typeName(qualified string) string {
	if index := strings.LastIndex(qualified, "."); index >= 0 {
		return qualified[index+1:]
	}
	return qualified
}

func anchor(value string) string { return strings.ToLower(value) }

func tableText(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	return strings.ReplaceAll(value, "\n", "<br>")
}

func write(path, contents string) error {
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
